config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :posts, only: [:index, :new, :create, :destroy] do
    resource :likes, only: [:create, :destroy]
  end

  root 'posts#index'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user

  validates_uniqueness_of :post, scope: :user # TODO: Add validation in DB
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  load_and_authorize_resource :post
  authorize_resource

  # POST /posts/1/likes
  def create
    @like = @post.likes.new(user_id: current_user.id)

    if @like.save
      render 'liked'
    else
      render 'error'
    end
  end

  # DELETE /posts/1/
  def destroy
    @like = @post.likes.find_by(user_id: current_user.id)
    @like.destroy if @like.present?
    render 'unliked'
  end

end

app/views/likes/liked.js.erb
$('#post-<%= @post.id %>-likes-count').html("<%= @post.likes.count %> likes");

setTimeout(() => {
  $('#post-<%= @post.id %>-like').html("<%= escape_javascript unlike_path(@post.id) %>");
}, 2000);

var heartIcon = $('#post-<%= @post.id %>-like .fa-heart')[0];
$(heartIcon).addClass('beat');

app/views/likes/unliked.js.erb
$('#post-<%= @post.id %>-like').html("<%= escape_javascript like_path(@post.id) %>");
$('#post-<%= @post.id %>-likes-count').html("<%= @post.likes.count %> likes");